### ISSUE TITLE
Enhance code completion

### ISSUE THREAD

**Issue by echebbi** [gemoc/ale-lang#182]
## Motivation

Current code completion offers little to no support and that makes writing code a pain.

## Proposed Solution

Enhancements are tracked in the following issues:
 - [ ] [#91 — Autocomplete openable classes](91)
 - [x] [~#92 — Autocomplete self's attributes and methods~](92)
 - [ ] [#176 — Autocomplete available collections when writing 'for' statement](176)
 - [ ] [#177 — Autocomplete right-hand side of assignments](177)
 - [ ] [#178 — Autocomplete empty statement](178)
 - [ ] [#179 — Autocomplete if conditions](179)
 - [ ] [#180 — Autocomplete while conditions](180)
 - [ ] [#181 — Autocomplete chained expressions](181)
