### ISSUE TITLE
Improve ALE documentation

### ISSUE THREAD

**Issue by echebbi** [gemoc/ale-lang#72]
## Motivation

It is currently sometimes hard to determine how to achieve simple things in ALE because the corresponding documentation is missing, misleading or incomplete.

See the following issues:
- [x] #21 — Missing documentation for attribute's modifiers
- [x] #29 — Missing documentation about initializing Sequence and OrderedSet
- [ ] #35 — documentation about collection services is incomplete
- [ ] #61 — document all available services

## Solution

Enhance current documentation. #59 <del>(currently WIP)</del> wants to address the issue.

I also suggest that, the next time we feel something is missing from the documentation, we add a comment to this issue so that we can keep track of it and fix it as soon as possible.

**Comment by echebbi** [comment]
Closing as documentation-related issues are now tracked in the documentation's repository, e.g.:
 - https://github.com/echebbi/ale-lang-docs/issues/6
 - https://github.com/echebbi/ale-lang-docs/issues/7
