### ISSUE TITLE
Open discussion on collection normalization

### ISSUE THREAD

**Issue by echebbi** [gemoc/ale-lang#74]
## Motivation

While working on #20 to fix a bug related to Sequence handling I noticed that depending on whether we are building the AST, interpreted the code, creating a local variable, a parameter, an attribute, etc. collections are not handled the same way, which can confuse tools, maintainers and users.

For instance:

 ```
class HelloWorld {

    Sequence(Integer) fieldInts;    // create an EList of type ClassType(BasicEList)
    0 ..* Integer multipleInts;

    @main
    def void run() {
        Sequence(Integer) list2 := Sequence{1, 2, 3};    // create an EList of type SequenceType

        self.fieldInts->sum();         // typechecker error, interpreter OK
        list2->sum();                  // typechecker OK, interpreter OK 
        self.multipleInts->sum();      // typechecker OK, interpreter OK
        self.mysum(list2);             // typechecker & interpreter errors
        self.mysum(self.fieldInts);    // typechecker & interpreter OK
        self.mysum(self.multipleInts); // typechecked error, interpreter OK
    }

    def int mysum(Sequence(Integer) list3) { // expects an EList of type ClassType(BasicElist)
        result := list3->sum();  // typechecked with an error but interpreted as expected
    }
}
```

Handling all those cases makes the code harder to understand and can lead to duplications.

## Discussion

As already discussed with @dvojtise I believe we should think of a unified way to handle collections (for both users and maintainers).

In my opinion, the best we could do is to consider that `min..max` and `Sequence(T)` are different concrete syntaxes of the same abstraction and hence:
 - either assume that they are different types (i.e. different methods, not interchangeable) and provide services to cast collections
 - or provide a kind of abstraction that would allow to use AQL Sequences and EMF EList in the exact same way.

Since we heavily rely on AQL to interpret expressions I don't know if the latter would be really easy to implement though.

@fcoulon, @pjeanjean, would you have any opinion on this?

## Related issues

 - [x] #3 Type checking error
 - [x] #10 Typecheck error when Sequence used in for loops
 - [x] #20 Resolution of methods with list parameters not working
 - [x] #42 Typecheck error when initializing Sequence
 - [ ] #44 support multiplicity on operation
 - [x] #75 Attributes of type Sequence cannot be initialized

**Comment by echebbi** [comment]
I think that, if maybe not perfect, the situation improved and offhand we have now:

- datatypes in the AST are represented by standard `EClassifier` (EMF)
- multiplicites are represented by properly setting bounds instead of creating an `EList` (#129)
- AQL's `IType` are inevitable when evaluating expressions (e.g. in the type checker or in the interpreter) but the `TypeChecker` and `ConvertType` classes make easy to convert EMF types to AQL and vice versa

As a matter of fact, collection support has greatly improved. I hence believe that this issue can now be closed.
